{% set name = "area-detector-handlers" %}
{% set version = "0.0.6" %}
{% set sha256 = "36f617dfc96006e8575e61ed78ca9f19421c0c0694e5aabdcc2cde40b0199834" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - dask
    - h5py
    - tifffile

test:
  imports:
    - area_detector_handlers

about:
  home: https://github.com/bluesky/area-detector-handlers
  license: BSD (3-clause)
  license_family: BSD
  license_file: LICENSE
  summary: DataBroker handlers for Area Detector
